# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: /#about
    weight: 10
  - name: Benchmarks
    url: /benchmarks
    weight: 20
  - name: Competitions
    identifier: comp
    weight: 40
  - name: NeurIPS 2022 Competition
    parent: comp
    url: /NeurIPS_2022
    weight: 10
  - name: NeurIPS 2021 Competition
    parent: comp
    url: /NeurIPS_2021
    weight: 20
  - name: NeurIPS 2021 Documentation
    parent: comp
    url: /NeurIPS_docs
    weight: 90
  - name: Team
    url: /team
    weight: 120
  - name: Documentation
    identifier: docs
    weight: 150
  - name: OpenProblems v1
    parent: docs
    url: https://github.com/openproblems-bio/openproblems/blob/main/CONTRIBUTING.md
  - name: OpenProblems v2
    parent: docs
    url: https://github.com/openproblems-bio/openproblems-v2/blob/main/CONTRIBUTING.md